version: '3'

services:
  work:
    container_name: php_server
    build:
      context: ./docker/php-apache
    volumes:
      - ${PROJECT_PATH}:/var/www/html:cached
      - node_modules:/var/www/html/node_modules
    environment:
      DB_HOST: 'mysql'

    ports:
      - ${WEB_PORT}:80
      - ${WEB_SSL_PORT}:443

#    links:
#      - mysql

  mysql:
    image: mysql:5.7
    volumes:
      - mysql_data_tasklist:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: ${TZ}
    ports:
      - ${DB_PORT}:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    links:
      - mysql
    ports:
      - ${PMA_PORT}:80

volumes:
  mysql_data_tasklist:
  node_modules: